name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    - name: Install Node.js dependencies
      run: npm ci

    - name: Lint Code Base
      uses: github/super-linter@v4.9.7
      env:
        VALIDATE_TYPESCRIPT_STANDARD: false
        VALIDATE_TYPESCRIPT_ES: true
        TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
